### ISSUE TITLE
Testat 0x01 am 23.11.16

### ISSUE THREAD

**Issue by cookiengineer** [INT-WAW/Slides#4]
Das erste Testat findet am 23.11. statt, im gleichen Raum wie immer (A008).

Da wir diese Woche zwei Mal zur Verfuegung haben, koennt ihr am Mittwoch voraussichtlich durchgehend am Projekt arbeiten. **Nutzt die Zeit am Mittwoch um auch Fragen zu stellen!**

**Testat am 23.11.**

Beginn ist wie gehabt, mit offenem Ende. Wer spaeter keine Zeit hat, bitte am gleichen Tag einfach vorher melden damit ich die Gruppenreihenfolge entsprechend sortieren kann. Sonst Pech gehabt. Erfahrungsstand von vorherigem Semester ist, dass die Testate bis ca. 19:00 dauern koennen.

Es gibt zwei Teile: Praxis und Theorie, jeweils mit 50% / 50% bewertet.

Praxisteil setzt voraus, dass ihr einen Pull-Request gemacht habt und diesen hier verlinkt - mit dem aktuellen Stand eures Projekts. Dies ist **bis zum Montag davor 12:00Uhr** zu erledigen, da ich ansonsten die Projekte nicht ansehen kann und dementsprechend gibt's dann keine oder weniger Punkte.

Theorieteil besteht aus den behandelten Themen, mit Fokus auf Verstaendnis von HTML5, CSS3 und ES6. Wenn ihr eine Bibliothek (z.B. jquery) verwendet habt, muesst ihr trotzdem erklaeren was es mit HTTP und XHR/fetch auf sich hat und was die darunterliegenden Konzepte voraussetzen.

**TODO fuer euch**

- [ ] Seht euch die Slides noch mal an
- [ ] Pull Request bis Montag, 21.11. um 12:00 Uhr
- [ ] Kommentar hier drunter mit Teamname und Pull-Request Direktlink.
- [ ] Seht euch die Slides noch mal an. No, srsly.

**Fehlende Pull-Requests von Teams**

- keine (alle haben eingereicht!)

**Erfolgreiche Pull-Requests von Teams**

- [Team314](https://github.com/INT-WAW/Boilerplate/pull/30)
- [Salty](https://github.com/INT-WAW/Boilerplate/pull/33)
- [Die Dudes](https://github.com/INT-WAW/Boilerplate/pull/35)
- [Das beste Team](https://github.com/INT-WAW/Boilerplate/pull/31)
- [imo](https://github.com/INT-WAW/Boilerplate/pull/36)
- [Error 404](https://github.com/INT-WAW/Boilerplate/pull/37)
- [Team Mystic](https://github.com/INT-WAW/Boilerplate/pull/38)
- [BoostedApes](https://github.com/INT-WAW/Boilerplate/pull/39)
- [ForkGitIt](https://github.com/INT-WAW/Boilerplate/pull/14)
- [Manatees](https://github.com/INT-WAW/Boilerplate/pull/40)

Bitte bedenkt, dass es Punktabzug gibt wenn ihr nicht eure Pull Requests eingereicht habt. Das ist dann wie ein nicht abgegebenes Pruefungsblatt - also 0 Punkte auf die ersten 50% der moeglichen Punkte :)

**Comment by cookiengineer** [comment]
🎉 Woop woop. Ihr habt noch ne Woche laenger fuer euer Projekt.  🎉

**Comment by dako314** [comment]
Gruppenname: Team314
Direktlink zu Pull-Request: https://github.com/INT-WAW/Boilerplate/pull/30

**Comment by erikmartens** [comment]
Gruppenname: Salty
Direktlink zu Pull-Request: https://github.com/INT-WAW/Boilerplate/pull/33

**Comment by 1520152NPHSM** [comment]
Gruppenname: Die Dudes
Direktlink zu Pull-Request: https://github.com/INT-WAW/Boilerplate/pull/35

**Comment by marcelherd** [comment]
Gruppenname: Das beste Team
https://github.com/INT-WAW/Boilerplate/pull/31

**Comment by cookiengineer** [comment]
Ich hab mal alle getagged, die das scheinbar verschlafen haben und/oder noch nicht eingereicht haben. Liste oben wurde aktualisiert.

**Comment by ouenlue** [comment]
Gruppe imo 
Direktlink: https://github.com/INT-WAW/Boilerplate/pull/36

**Comment by sabe111** [comment]
Gruppe Error404
Link: https://github.com/INT-WAW/Boilerplate/pull/37

**Comment by FriederikeHerbold** [comment]
Gruppe Team Mysitc
Link: https://github.com/INT-WAW/Boilerplate/pull/38

**Comment by Lucas964** [comment]
Gruppe: BoostedApes
Link: https://github.com/INT-WAW/Boilerplate/pull/39

**Comment by cookiengineer** [comment]
Wieder updated, fehlen noch ForkGitIt und die Manatees.

**Comment by limecakeio** [comment]
Let's not get the pressure ahead of ourselves ;)

Link: https://github.com/INT-WAW/Boilerplate/pull/14

**Comment by freakdran** [comment]
Gruppe: Manatees
Link: [INT-WAW/Boilerplate#40](https://github.com/INT-WAW/Boilerplate/pull/40)

**Comment by Emmeris** [comment]
# **!!!GRUPPE MANATEES MÖCHTE, MÜSSTE, SOLLTE BITTE FRÜHER DRAN KOMMEN, DA FreakDran FRÜHER NACH HAUSE MUSS**
# **BITTE ALS NÄCHSTES WENN MÖGLICH!!!**
